version: "3.3"

services:

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./www/assets/:/www/assets
    restart: unless-stopped
    ports:
      - "8423:8080"
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default      
      
      
